### ISSUE TITLE
TASK: Create `wiki` module

### ISSUE THREAD

**Issue by widal001** [widal001/wiki-graph#1]
## Summary

Create a `wiki` module that formats the url for the Wikipedia API and then queries the wikipedia API for a given url

## TODOs

- [ ] Create a `WikiArticle` interface with the following functions
  - [ ] `FormatURL()` generates the URL for the Wikipedia API call
  - [ ] `FetchData()` queries the API and 
  - [ ] `ParseResult()` 
- [ ] Create a 

## Definition of Done

- [ ] A user can supply an article to the `WikiArticle` and
